### ISSUE TITLE
Single board: why do buzzers just click now?

### ISSUE THREAD

**Issue by dotMR** [dotMR/LugeRacerTimer#16]

**Comment by rmicallef** [comment]
I wonder whether a 3:8 decoder would be faster than a shift register.

**Comment by dotMR** [comment]
Re: buzzer, Ryan says:
"The buzzer needs to be driven with a square wave. I'm not sure how fast the register can clock in data, but you might be able to drive the buzzer off the register pin if it's fast enough."

btw, the volume is also really low on the buzzer. And it happens on the main board buzzer as well, which makes me think it's more specific to the buzzers I got than the shift register.

Using these currently:
https://www.tinkersoup.de/en/sound-audio/piezo-buzzer-speaker-a-pc-mount-12mm-2-048khz/a-1227/

**Comment by dotMR** [comment]
Re: decoder
Not sure about the decoder - I would guess it would be faster though as less serial bit banging.

**Comment by dotMR** [comment]
woops:
Looks like we need to supply the +5V @ 2048Hz for speaker output.

"Sound output Min. 85 (Typical 95) dBA Distance at 10cm (A-weight free air).
Applying rated voltage of 2048 Hz, square
wave, 1/2 duty."
http://dlnmh9ip6v2uc.cloudfront.net/datasheets/Components/General/cem-1203-42-.pdf

Note: check tone library
http://arduino.cc/en/reference/tone

**Comment by rmicallef** [comment]
Isn't this what we did for the other buzzer?

**Comment by dotMR** [comment]
decoder conversation moved to new issue #17 

Yeah, we did something similar with the other buzzing, but i'm using the same code. [~Line 509](https://github.com/dotMR/LugeRacerTimer/blob/shift/src/LugeRacerTimer.ino#L509)

Looks like buzzers I bought here are Sparkfun parts, so we'd likely run into the same issue with any others we'll order in the future.

I'll try the tone library and see if anything changes.

**Comment by dotMR** [comment]
Fixed in my current 'shift' branch 71fe012126ceeb9e40535c947589b4647b63c7d0

**Comment by rmicallef** [comment]
So it's working through the shift register now?  Sweet.
