### ISSUE TITLE
Laser cut new top for timer box

### ISSUE THREAD

**Issue by dotMR** [dotMR/LugeRacerTimer#4]
Ryan has a new design in mind
- smaller opening for 7-segment display rather than previous LCD
- 2 voltmeter openings (one for each finish-line sensor)

**Comment by ssbla** [comment]
Most current version from Ryan:
![luge timer panel](https://cloud.githubusercontent.com/assets/3236328/5733072/3d5077a4-9b9d-11e4-9f6c-8c4dce102fc8.gif)
